language: node_js
node_js:
    - '6'
sudo: false

script:
    - npm t
    - npm run test:flow
    - npm run coverage

after_success:
    - npm run coverage
    - bash <(curl -s https://codecov.io/bash)
    - npm run build:docs
