// flow-typed signature: 7c730b999f1faa38fd4f57286dda4553
// flow-typed version: <<STUB>>/ws_v^1.1.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ws/lib/BufferPool' {
  declare module.exports: any;
}

declare module 'ws/lib/BufferUtil.fallback' {
  declare module.exports: any;
}

declare module 'ws/lib/BufferUtil' {
  declare module.exports: any;
}

declare module 'ws/lib/ErrorCodes' {
  declare module.exports: any;
}

declare module 'ws/lib/Extensions' {
  declare module.exports: any;
}

declare module 'ws/lib/PerMessageDeflate' {
  declare module.exports: any;
}

declare module 'ws/lib/Receiver.hixie' {
  declare module.exports: any;
}

declare module 'ws/lib/Receiver' {
  declare module.exports: any;
}

declare module 'ws/lib/Sender.hixie' {
  declare module.exports: any;
}

declare module 'ws/lib/Sender' {
  declare module.exports: any;
}

declare module 'ws/lib/Validation.fallback' {
  declare module.exports: any;
}

declare module 'ws/lib/Validation' {
  declare module.exports: any;
}

declare module 'ws/lib/WebSocket' {
  declare module.exports: any;
}

declare module 'ws/lib/WebSocketServer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ws/index' {
  declare module.exports: $Exports<'ws'>;
}
declare module 'ws/index.js' {
  declare module.exports: $Exports<'ws'>;
}
declare module 'ws/lib/BufferPool.js' {
  declare module.exports: $Exports<'ws/lib/BufferPool'>;
}
declare module 'ws/lib/BufferUtil.fallback.js' {
  declare module.exports: $Exports<'ws/lib/BufferUtil.fallback'>;
}
declare module 'ws/lib/BufferUtil.js' {
  declare module.exports: $Exports<'ws/lib/BufferUtil'>;
}
declare module 'ws/lib/ErrorCodes.js' {
  declare module.exports: $Exports<'ws/lib/ErrorCodes'>;
}
declare module 'ws/lib/Extensions.js' {
  declare module.exports: $Exports<'ws/lib/Extensions'>;
}
declare module 'ws/lib/PerMessageDeflate.js' {
  declare module.exports: $Exports<'ws/lib/PerMessageDeflate'>;
}
declare module 'ws/lib/Receiver.hixie.js' {
  declare module.exports: $Exports<'ws/lib/Receiver.hixie'>;
}
declare module 'ws/lib/Receiver.js' {
  declare module.exports: $Exports<'ws/lib/Receiver'>;
}
declare module 'ws/lib/Sender.hixie.js' {
  declare module.exports: $Exports<'ws/lib/Sender.hixie'>;
}
declare module 'ws/lib/Sender.js' {
  declare module.exports: $Exports<'ws/lib/Sender'>;
}
declare module 'ws/lib/Validation.fallback.js' {
  declare module.exports: $Exports<'ws/lib/Validation.fallback'>;
}
declare module 'ws/lib/Validation.js' {
  declare module.exports: $Exports<'ws/lib/Validation'>;
}
declare module 'ws/lib/WebSocket.js' {
  declare module.exports: $Exports<'ws/lib/WebSocket'>;
}
declare module 'ws/lib/WebSocketServer.js' {
  declare module.exports: $Exports<'ws/lib/WebSocketServer'>;
}
